/*Product Constant*/
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'

/*Cart Constant*/
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const RESET_CART_ITEM_AFTER_ORDER = 'RESET_CART_ITEM_AFTER_ORDER';
export const SAVED_SHIPPING_ADDRESS = 'SAVED_SHIPPING_ADDRESS';
export const CART_PAYMENT_METHOD = 'CART_PAYMENT_METHOD';


/*User Constant*/
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET';

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_RESET = 'UPDATE_USER_PROFILE_RESET';

/*Order Constant*/
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';


export const REMOVE_ORDER_SUCCESS = 'REMOVE_ORDER_SUCCESS';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET';


/*Order pay*/
export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST';
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS';
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL';
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET';

/*Get User Orders*/
export const USER_ALL_ORDERS_REQUEST = 'USER_ALL_ORDERS_REQUEST';
export const USER_ALL_ORDERS_SUCCESS = 'USER_ALL_ORDERS_SUCCESS';
export const USER_ALL_ORDERS_FAIL = 'USER_ALL_ORDERS_FAIL';


/*Get Placed Order Details*/
export const GET_PLACED_ORDER_DETAILS_REQUEST = 'GET_PLACED_ORDER_DETAILS_REQUEST';
export const GET_PLACED_ORDER_DETAILS_SUCCESS = 'GET_PLACED_ORDER_DETAILS_SUCCESS';
export const GET_PLACED_ORDER_DETAILS_FAIL = 'GET_PLACED_ORDER_DETAILS_FAIL';
export const GET_PLACED_ORDER_DETAILS_RESET = 'GET_PLACED_ORDER_DETAILS_RESET';


/*ADMIN USER CONSTANT*/
export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST';
export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS';
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL';
export const ADMIN_USER_LIST_RESET = 'ADMIN_USER_LIST_RESET';


export const ADMIN_USER_DELETE_REQUEST = 'ADMIN_USER_DELETE_REQUEST';
export const ADMIN_USER_DELETE_SUCCESS = 'ADMIN_USER_DELETE_SUCCESS';
export const ADMIN_USER_DELETE_FAIL = 'ADMIN_USER_DELETE_FAIL';


export const ADMIN_GET_USER_BY_ID_REQUEST = 'ADMIN_GET_USER_BY_ID_REQUEST';
export const ADMIN_GET_USER_BY_ID_SUCCESS = 'ADMIN_GET_USER_BY_ID_SUCCESS';
export const ADMIN_GET_USER_BY_ID_FAIL = 'ADMIN_GET_USER_BYID_FAIL';
export const ADMIN_GET_USER_BY_ID_RESET = 'ADMIN_GET_USER_BYID_RESET';


export const ADMIN_USER_UPDATE_REQUEST = 'ADMIN_USER_UPDATE_REQUEST';
export const ADMIN_USER_UPDATE_SUCCESS = 'ADMIN_USER_UPDATE_SUCCESS';
export const ADMIN_USER_UPDATE_FAIL = 'ADMIN_USER_UPDATE_FAIL';


/*ADMIN ORDER CONSTANT*/

export const ADMIN_GET_ORDER_REQUEST = 'ADMIN_GET_ORDER_REQUEST';
export const ADMIN_GET_ORDER_SUCCESS = 'ADMIN_GET_ORDER_SUCCESS';
export const ADMIN_GET_ORDER_FAIL = 'ADMIN_GET_ORDER_FAIL';



/*ADMIN PRODUCT CONSTANT*/
export const ADMIN_RESET_PRODUCT_DETAILS = 'ADMIN_RESET_PRODUCT_DETAILS';

export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAIL = 'ADMIN_DELETE_PRODUCT_FAIL';

export const ADMIN_UPDATE_PRODUCT_REQUEST = 'ADMIN_UPDATE_PRODUCT_REQUEST';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAIL = 'ADMIN_UPDATE_PRODUCT_FAIL';


export const ADMIN_CREATE_PRODUCT_REQUEST = 'ADMIN_CREATE_PRODUCT_REQUEST';
export const ADMIN_CREATE_PRODUCT_SUCCESS = 'ADMIN_CREATE_PRODUCT_SUCCESS';
export const ADMIN_CREATE_PRODUCT_FAIL = 'ADMIN_CREATE_PRODUCT_FAIL';
export const ADMIN_CREATE_PRODUCT_RESET = 'ADMIN_CREATE_PRODUCT_RESET';

/*REVIEWS CONSTANT*/
export const CREATE_PRODUCT_REVIEW_REQUEST = 'CREATE_PRODUCT_REVIEW_REQUEST';
export const CREATE_PRODUCT_REVIEW_SUCCESS = 'CREATE_PRODUCT_REVIEW_SUCCESS';
export const CREATE_PRODUCT_REVIEW_FAIL = 'CREATE_PRODUCT_REVIEW_FAIL';
export const CREATE_PRODUCT_REVIEW_RESET = 'CREATE_PRODUCT_REVIEW_RESET';


/*TOP PRODUCT CONSTANT*/
export const GET_TOP_PRODUCT_REQUEST = 'GET_TOP_PRODUCT_REQUEST';
export const GET_TOP_PRODUCT_SUCCESS = 'GET_TOP_PRODUCT_SUCCESS';
export const GET_TOP_PRODUCT_FAIL = 'GET_TOP_PRODUCT_FAIL';


